### ISSUE TITLE
Fresh Project, user relation isn't created automatically

### ISSUE THREAD

**Issue by derrickmehaffy** [Lith/strapi-plugin-notification-expo#1]
Strapi: v3.5.0
Node: v12
NPM: v6
OS: Linux Mint 20.1 (Ubuntu 20.04.1)

Error message:

```
[2021-02-18T21:21:45.854Z] error Error: The attribute `expotokens` is missing in the model User (plugin - users-permissions)
    at Object.getNature (/home/dmehaffy/Development/testAS34/node_modules/strapi-utils/lib/models.js:144:15)
    at /home/dmehaffy/Development/testAS34/node_modules/strapi-connector-bookshelf/lib/mount-models.js:181:21
    at Array.forEach (<anonymous>)
    at updateModel (/home/dmehaffy/Development/testAS34/node_modules/strapi-connector-bookshelf/lib/mount-models.js:174:40)
    at async module.exports (/home/dmehaffy/Development/testAS34/node_modules/strapi-connector-bookshelf/lib/mount-models.js:691:28)
    at async Promise.all (index 3)
    at async Promise.all (index 3)
    at async mountConnection (/home/dmehaffy/Development/testAS34/node_modules/strapi-connector-bookshelf/lib/index.js:84:31)
    at async Promise.all (index 0)
    at async Object.initialize (/home/dmehaffy/Development/testAS34/node_modules/strapi-database/lib/connector-registry.js:30:9)
    at async DatabaseManager.initialize (/home/dmehaffy/Development/testAS34/node_modules/strapi-database/lib/database-manager.js:36:5)
    at async Strapi.load (/home/dmehaffy/Development/testAS34/node_modules/strapi/lib/Strapi.js:339:5)
    at async Strapi.start (/home/dmehaffy/Development/testAS34/node_modules/strapi/lib/Strapi.js:191:9)
error Command failed with exit code 1.
```

PS: I did test on a fresh v3.4.6 project as well, but didn't expect a change since functionally there wasn't any changes that should affect this plugin.

Screenshots:

![image](https://user-images.githubusercontent.com/8593673/108423534-367cb200-71f5-11eb-9583-01943a86bb5b.png)

![image](https://user-images.githubusercontent.com/8593673/108423566-3d0b2980-71f5-11eb-9f83-5bc5c5b9a026.png)

![image](https://user-images.githubusercontent.com/8593673/108423585-42687400-71f5-11eb-805b-7287a93d591e.png)

Test Project on v3.4.6:

[testAS34.zip](https://github.com/Lith/strapi-plugin-notification-expo/files/6005981/testAS34.zip)

**Comment by derrickmehaffy** [comment]
I was trying to find the code we use to copy the `User.settings.json` into `./extensions/users-permissions/models/` when the Content-Type builder builds a relation from a normal model to the User model but can't seem to find it :thinking:

**Comment by derrickmehaffy** [comment]
Alternative to the relation type you are using, you could setup the expotoken model as a oneWay or manyWay relation type that would cut the need to have this model override

**Comment by Lith** [comment]
Yes, I've seen that  😆  I've add into the README.md this additional setup step : 
- https://github.com/Lith/strapi-plugin-notification-expo#3-edit-users-permissions-models-settings

A user can have many expotokens, so I can use the "manyWay" type and this will do the same thing ?

I should prefer do not touch to the `users-permissions` model and have a system than can working alone.
I will try tomorrow :)

**Comment by Lith** [comment]
#3 is working well ! I've updated the README with now 3 step to install instead of 5.
Thanks :)

**Comment by derrickmehaffy** [comment]
My fix is for a one Way relation but you can modify it to be a many way (just change the model key to a collection key)

The only downside to this system is you can't fetch keys by looking at the user model, only the reverse,  you can fetch keys by filtering for the user.

**Comment by Lith** [comment]
We don't need to fetch tokens from `users` table , we only need to list all tokens from `expotokens` table of selected user(s).

I need to learn more about relation type, maybe add some examples in the documentation with draw and a database view ^^
